file:
  upload_local_path: /test.jlgwzz.com/
  show_url:  http://39.97.232.184:18080/testFile/
  cms_path: cms
  gwzz_path: gwzz
  jodit:
    path: /test.jlgwzz.com/jodit/
    base_url: http://39.97.232.184:18080/testFile/jodit/
    path_article: /test.jlgwzz.com/jodit/article
    base_url_article: http://39.97.232.184:18080/testFile/jodit/article